//
//  HundredQuestions.swift
//  MyFirstTvApp
//
//  Created by Robert Møller on 04/03/2023.
//

import Foundation

class HundredQuestions {
    static let part1: [Card] = [
        Card(title: "Hvem i rommet", emoji: "📵",text: "Er alltid på mobilen?"),
        Card(title: "Hvem i rommet", emoji: "💪",text: "Har mest viljestyrke?"),
        Card(title: "Hvem i rommet", emoji: "🍺",text: "Er best på å styrte?"),
        Card(title: "Hvem i rommet", emoji: "🚘",text: "Er dårligst sjåfør?"),
        Card(title: "Hvem i rommet", emoji: "🐗",text: "Er mest vill?"),
        Card(title: "Hvem i rommet", emoji: "💸",text: "Spanderer alltid på fylla?"),
        Card(title: "Hvem i rommet", emoji: "🌊",text: "Er kåtest?"),
        Card(title: "Hvem i rommet", emoji: "🤓",text: "Er flinkest på skolen?"),
        Card(title: "Hvem i rommet", emoji: "🤲",text: "Tar seg mest på puppene?"),
        Card(title: "Hvem i rommet", emoji: "🎅",text: "Trodde lengst på julenissen?"),
        Card(title: "10 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "⏳",text: "Mest ubesluttsom?"),
        Card(title: "Hvem i rommet", emoji: "🥃",text: "Har høyest toleranse?"),
        Card(title: "Hvem i rommet", emoji: "✌️",text: "Er mest rettferdig?"),
        Card(title: "Hvem i rommet", emoji: "😏",text: "Lager de sjukeste lydene i senga?"),
        Card(title: "Hvem i rommet", emoji: "🎗",text: "Gir mest til veldedighet?"),
        Card(title: "Hvem i rommet", emoji: "🙄",text: "Er mest overlegen?"),
        Card(title: "Hvem i rommet", emoji: "💯",text: "Kommer til å lykkes best i livet?"),
        Card(title: "Hvem i rommet", emoji: "🪂",text: "Er en adrenalin junkie?"),
        Card(title: "Hvem i rommet", emoji: "🏆",text: "Googler seg selv oftest?"),
        Card(title: "Hvem i rommet", emoji: "😇",text: "Er lykkeligst?"),
        Card(title: "20 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "🕵️‍♀️",text: "Er den verste stalkeren?"),
        Card(title: "Hvem i rommet", emoji: "🎻",text: "Har dårligst musikksmak?"),
        Card(title: "Hvem i rommet", emoji: "🥱",text: "Kommer til og sovne med en pizza i hånden?"),
        Card(title: "Hvem i rommet", emoji: "🚿",text: "Har shava og er forberedt på alt?"),
        Card(title: "Hvem i rommet", emoji: "🎖",text: "Har hatt seg med flest?"),
        Card(title: "Hvem i rommet", emoji: "🏋️‍♀️",text: "Er sterkest?"),
        Card(title: "Hvem i rommet", emoji: "🤮",text: "Kommer mest sannsynlig til å spy i kveld?"),
        Card(title: "Hvem i rommet", emoji: "🗣",text: "Har finest dialekt?"),
        Card(title: "Hvem i rommet", emoji: "🔮",text: "Havner på gata?"),
        Card(title: "Hvem i rommet", emoji: "☀️",text: "Lyser opp rommet?"),
        Card(title: "30 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "🦄",text: "Skiller seg mest ut i mengden?"),
        Card(title: "Hvem i rommet", emoji: "😎",text: "Har størst kjendisfaktor?"),
        Card(title: "Hvem i rommet", emoji: "🧗‍♂️",text: "Er mest eventyrlysten?"),
        Card(title: "Hvem i rommet", emoji: "👓",text: "Har best syn?"),
        Card(title: "Hvem i rommet", emoji: "💤",text: "Snorker mest?"),
        Card(title: "Hvem i rommet", emoji: "💩",text: "Slipper de verste fisene?"),
        Card(title: "Hvem i rommet", emoji: "🙋‍♂️",text: "Kunne levd best med bare en arm og ett ben?"),
        Card(title: "Hvem i rommet", emoji: "🏃‍♂️",text: "Løper fortest?"),
        Card(title: "Hvem i rommet", emoji: "🤓",text: "Nørder mest?"),
        Card(title: "Hvem i rommet", emoji: "💍",text: "Kommer til å gifte seg først?"),
        Card(title: "40 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "🛫",text: "Hvem er medlem av Mile High Club?"),
        Card(title: "Hvem i rommet", emoji: "💰",text: "Kommer til å bli rikest?"),
        Card(title: "Hvem i rommet", emoji: "💋",text: "Er den beste til å kysse?"),
        Card(title: "Hvem i rommet", emoji: "🐾",text: "Tar med seg noen hjem i kveld?"),
        Card(title: "Hvem i rommet", emoji: "🌵",text: "Stikker mest?"),
        Card(title: "Hvem i rommet", emoji: "🐎",text: "Rir best?"),
        Card(title: "Hvem i rommet", emoji: "🏡",text: "Bor finest?"),
        Card(title: "Hvem i rommet", emoji: "🥽",text: "Er mest positiv til nye utfordringer?"),
        Card(title: "Hvem i rommet", emoji: "👨",text: "Er en av gutta?"),
        Card(title: "Hvem i rommet", emoji: "📸",text: "Tar flest selfies?"),
        Card(title: "50 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "🔚",text: "Kommer raskest?"),
        Card(title: "Hvem i rommet", emoji: "🏝",text: "Kunne du vært på en øde øy med?"),
        Card(title: "Hvem i rommet", emoji: "🥶",text: "Har lettest for å bryte isen med noen ukjente?"),
        Card(title: "Hvem i rommet", emoji: "🎓",text: "Kommer mest sannsynlig til å stryke et fag dette semesteret?"),
        Card(title: "Hvem i rommet", emoji: "🚵",text: "Er mest sporty?"),
        Card(title: "Hvem i rommet", emoji: "🔥",text: "Lager best stemning på vors?"),
        Card(title: "Hvem i rommet", emoji: "👀",text: "Har de vakreste øyene?"),
        Card(title: "Hvem i rommet", emoji: "❌",text: "Kommer seg ikke inn på byen i kveld?"),
        Card(title: "Hvem i rommet", emoji: "🛏",text: "Er best i senga?"),
        Card(title: "Hvem i rommet", emoji: "🆘",text: "Er mest drita?"),
        Card(title: "60 spørsmål", text:"🍻SKÅL🍻"),
        
        Card(title: "Hvem i rommet", emoji: "🏫",text: "Har best karakterer nå?"),
        Card(title: "Hvem i rommet", emoji: "🎮",text: "Er den svetteste gameren?"),
        Card(title: "Hvem i rommet", emoji: "🐻",text: "Har best sjanse til å overleve mot en bjørn?"),
        Card(title: "Hvem i rommet", emoji: "👓",text: "Kler briller best?"),
        Card(title: "Hvem i rommet", emoji: "🥺",text: "Er snillest?"),
        Card(title: "Hvem i rommet", emoji: "👌",text: "Har hooket med flest?"),
        Card(title: "Hvem i rommet", emoji: "💼",text: "Er mest klar for arbeidslivet?"),
        Card(title: "Hvem i rommet", emoji: "👱‍♀️",text: "Har flest blonde øyeblikk?"),
        Card(title: "Hvem i rommet", emoji: "😡",text: "Har mest temperament?"),
        Card(title: "Hvem i rommet", emoji: "😘",text: "Holder på med flere samtidig?"),
        Card(title: "70 spørsmål", text:"🍻SKÅL🍻"),
        
        Card(title: "Hvem i rommet", emoji: "😌",text: "Selv tror den er morsomst?"),
        Card(title: "Hvem i rommet", emoji: "💔",text: "Har hatt flest kjærester?"),
        Card(title: "Hvem i rommet", emoji: "🐭",text: "Er en liten luremus?"),
        Card(title: "Hvem i rommet", emoji: "🎧",text: "Har verst musikksmak?"),
        Card(title: "Hvem i rommet", emoji: "🎭",text: "Har mest humørsvingninger?"),
        Card(title: "Hvem i rommet", emoji: "😵",text: "Synger styggest?"),
        Card(title: "Hvem i rommet", emoji: "💈",text: "Har mest kroppshår?"),
        Card(title: "Hvem i rommet", emoji: "☠️",text: "Er tøffest i trynet?"),
        Card(title: "Hvem i rommet", emoji: "💄",text: "Har finest lepper?"),
        Card(title: "Hvem i rommet", emoji: "🔞",text: "Har den mest skitne nettleserhistorikken?"),
        Card(title: "80 spørsmål", text:"🍻SKÅL🍻"),
        
        Card(title: "Hvem i rommet", emoji: "🚇",text: "Er best kjent i byen dere er i?"),
        Card(title: "Hvem i rommet", emoji: "🚑",text: "Hvem har vært flest ganger på legevakten det siste året?"),
        Card(title: "Hvem i rommet", emoji: "💃",text: "Hadde gjort det best på skal vi danse?"),
        Card(title: "Hvem i rommet", emoji: "👨‍👩‍👦",text: "Kunne du aldri hatt med i et familieselskap?"),
        Card(title: "Hvem i rommet", emoji: "🤯",text: "Tåler smerte best?"),
        Card(title: "Hvem i rommet", emoji: "🤣",text: "Driter seg alltid ut?"),
        Card(title: "Hvem i rommet", emoji: "🏆",text: "Er flinkest til å sjekke opp på byen?"),
        Card(title: "Hvem i rommet", emoji: "🚁",text: "Er mest spontan?"),
        Card(title: "Hvem i rommet", emoji: "🔮",text: "Tror på synske?"),
        Card(title: "Hvem i rommet", emoji: "📞",text: "Har kortest telefonsamtaler?"),
        Card(title: "90 spørsmål", text:"🍻SKÅL🍻"),
        
        Card(title: "Hvem i rommet", emoji: "💰",text: "Har størst lommebok?"),
        Card(title: "Hvem i rommet", emoji: "🚽",text: "Ser på mest reality-drit?"),
        Card(title: "Hvem i rommet", emoji: "💙",text: "Har tatt kongla flest ganger?"),
        Card(title: "Hvem i rommet", emoji: "🦶",text: "Har størst føtter?"),
        Card(title: "Hvem i rommet", emoji: "🕵️‍♂️",text: "Er mest mystisk?"),
        Card(title: "Hvem i rommet", emoji: "🙊",text: "Minner mest om en ape?"),
        Card(title: "Hvem i rommet", emoji: "💌",text: "Har hatt flest kjønnssjukdommer?"),
        Card(title: "Hvem i rommet", emoji: "🏃",text: "Tar alltid en for laget?"),
        Card(title: "Hvem i rommet", emoji: "😷",text: "Er mest frekk i kjeften?"),
        Card(title: "Hvem i rommet", emoji: "💯",text: "Skal ta bonski sammen med deg?"),
        Card(title: "100 spørsmål", text: "🍻SKÅL🍻"),
    ]
    
   static let part2: [Card] = [
        Card(title: "Hvem i rommet", emoji: "👪", text: "Ville du helst presentert for foreldrene dine?"),
        Card(title: "Hvem i rommet", emoji: "👴", text: "Prøver seg på den eldste i kveld?"),
        Card(title: "Hvem i rommet", emoji: "🛀", text: "Er lengst i dusjen?"),
        Card(title: "Hvem i rommet", emoji: "🍼", text: "Er klar for å få barn?"),
        Card(title: "Hvem i rommet", emoji: "🆙", text: "Liker å bruke butplug?"),
        Card(title: "Hvem i rommet", emoji: "👨‍👩‍👦", text:"Kommer til å flytte hjem igjen til foreldrene sine?"),
        Card(title: "Hvem i rommet", emoji: "🃏", text: "Jukser mest?"),
        Card(title: "Hvem i rommet", emoji: "🍒", text: "Har de mest spennende brystene?"),
        Card(title: "Hvem i rommet", emoji: "🧥", text: "Kler seg best?"),
        Card(title: "Hvem i rommet", emoji: "🐭", text: "Snuser mest?"),
        Card(title: "10 spørsmål", text: "🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "🎰", text: "Kjøper flest skrapelodd i løpet av et år?"),
        Card(title: "Hvem i rommet", emoji: "🐷", text: "Er en skikkelig sofagris?"),
        Card(title: "Hvem i rommet", emoji: "🛌", text: "Tar mest initiativ i sengen?"),
        Card(title: "Hvem i rommet", emoji: "🍻", text: "Er mest på Heidis?"),
        Card(title: "Hvem i rommet", emoji: "🐴", text: "Rir best?"),
        Card(title: "Hvem i rommet", emoji: "🤑", text: "Er mest gjerrig?"),
        Card(title: "Hvem i rommet", emoji: "🕵", text: "Du har et lite øye til?"),
        Card(title: "Hvem i rommet", emoji: "🚌", text: "Hvem hadde flest anmerkninger på ungdomsskolen?"),
        Card(title: "Hvem i rommet", emoji: "😹", text: "Har den sjukeste latteren?"),
        Card(title: "Hvem i rommet", emoji: "📚", text: "Er minst skoleflink?"),
        Card(title: "20 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "📝", text: "Har en liggeliste på notater?"),
        Card(title: "Hvem i rommet", emoji: "🍣", text: "Kunne spist mest sushi?"),
        Card(title: "Hvem i rommet", emoji: "❗️", text:"Blir oftest tatt på fersken av foreldrene?"),
        Card(title: "Hvem i rommet", emoji: "😎", text: "Er kulest?"),
        Card(title: "Hvem i rommet", emoji: "🛍", text: "Er mest bortskjemt?"),
        Card(title: "Hvem i rommet", emoji: "😼", text: "Har lyst å komme i buksen på noen i kveld?"),
        Card(title: "Hvem i rommet", emoji: "👗", text: "Har finest antrekk?"),
        Card(title: "Hvem i rommet", emoji: "👟", text: "Har minst føtter?"),
        Card(title: "Hvem i rommet", emoji: "😡", text: "Blir raskast sjalu?"),
        Card(title: "Hvem i rommet", emoji: "🍉", text: "Tar seg mest på brystene?"),
        Card(title: "30 spørsmål", text: "🍻SKÅL🍻"),
        
        Card(title: "Hvem i rommet", emoji: "👰", text: "Er mest uskyldig?"),
        Card(title: "Hvem i rommet", emoji: "🙋", text: "Blir gravid først?"),
        Card(title: "Hvem i rommet", emoji: "🤪", text: "Er mest crazy?"),
        Card(title: "Hvem i rommet", emoji: "👤", text: "Er mest bredskuldret?"),
        Card(title: "Hvem i rommet", emoji: "👯", text: "Har finest legger?"),
        Card(title: "Hvem i rommet", emoji: "😂", text: "Er morsomst?"),
        Card(title: "Hvem i rommet", emoji: "👶", text: "Du får vakrest barn sammen med?"),
        Card(title: "Hvem i rommet", emoji: "📍", text: "Er minst flink å bruke prevensjon?"),
        Card(title: "Hvem i rommet", emoji: "🍆", text: "Har størst penis?"),
        Card(title: "Hvem i rommet", emoji: "👐", text: "Er mest glad i pupper?"),
        Card(title: "40 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "🎓", text: "Har best karakterer fra videregående?"),
        Card(title: "Hvem i rommet", emoji: "👑", text: "Er mest populær?"),
        Card(title: "Hvem i rommet", emoji: "🏅", text: "Har hatt flest orgasmer?"),
        Card(title: "Hvem i rommet", emoji: "💅", text: "Er mest opptatt av utseende?"),
        Card(title: "Hvem i rommet", emoji: "🐎", text: "Er den største sossen?"),
        Card(title: "Hvem i rommet", emoji: "😵", text: "Er frekkest?"),
        Card(title: "Hvem i rommet", emoji: "💪", text: "Trener mest?"),
        Card(title: "Hvem i rommet", emoji: "🏘", text: "Har flest hytter?"),
        Card(title: "Hvem i rommet", emoji: "💍", text: "Gifter seg først?"),
        Card(title: "Hvem i rommet", emoji: "🆔", text: "Brukt falsk legitimasjon flest ganger?"),
        Card(title: "50 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "📽", text: "Har flest nakenbilder på telefonen sin?"),
        Card(title: "Hvem i rommet", emoji: "🤳", text: "Har flest filmer av seg selv på mobilen?"),
        Card(title: "Hvem i rommet", emoji: "😷", text: "Spyr i kveld?"),
        Card(title: "Hvem i rommet", emoji: "😔", text: "Har mest FOMO? (Fear of Missing Tut)"),
        Card(title: "Hvem i rommet", emoji: "👵", text: "Har hatt seg med flest eldre?"),
        Card(title: "Hvem i rommet", emoji: "🏠", text: "Har det ryddigste rommet?"),
        Card(title: "Hvem i rommet", emoji: "✈️", text:"Er mest spontan?"),
        Card(title: "Hvem i rommet", emoji: "👠", text: "Har lengst tånegler?"),
        Card(title: "Hvem i rommet", emoji: "🚒", text: "Har blitt pumpa?"),
        Card(title: "Hvem i rommet", emoji: "🎷", text: "Spiller et instrument best?"),
        Card(title: "60 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "🚼", text: "Debuterte først?"),
        Card(title: "Hvem i rommet", emoji: "⛺️", text:"Hatt seg i et telt?"),
        Card(title: "Hvem i rommet", emoji: "🧑‍🎓", text:"Slutter på studiet først?"),
        Card(title: "Hvem i rommet", emoji: "🎥", text: "Kunne vært en Hollywoodskuespiller?"),
        Card(title: "Hvem i rommet", emoji: "🍳", text: "Bruker minst penger på mat?"),
        Card(title: "Hvem i rommet", emoji: "😶", text: "Er mest fornøyd med sitt eget utseende?"),
        Card(title: "Hvem i rommet", emoji: "👨", text: "Blir pappa først?"),
        Card(title: "Hvem i rommet", emoji: "🐓", text: "Ønsker seg høne i kveld?"),
        Card(title: "Hvem i rommet", emoji: "🥗", text: "Spiser sunnest?"),
        Card(title: "Hvem i rommet", emoji: "🎬", text: "Har flest Instagram følgere?"),
        Card(title: "70 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "✝", text: "Mest religiøs?"),
        Card(title: "Hvem i rommet", emoji: "🔝", text: "Er høyest?"),
        Card(title: "Hvem i rommet", emoji: "💇", text: "Har finest frisyre?"),
        Card(title: "Hvem i rommet", emoji: "🧠", text: "Er eldst mentalt?"),
        Card(title: "Hvem i rommet", emoji: "⚾️", text:"Størst baller?"),
        Card(title: "Hvem i rommet", emoji: "📺", text: "Kunne vært med på Paradise Hotel?"),
        Card(title: "Hvem i rommet", emoji: "🥃", text: "Tåler mest alkohol?"),
        Card(title: "Hvem i rommet", emoji: "🤓", text: "Er mest dedikert?"),
        Card(title: "Hvem i rommet", emoji: "🍾", text: "Drikker raskest?"),
        Card(title: "Hvem i rommet", emoji: "💇‍♀️", text:"Er finest på håret?"),
        Card(title: "80 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "😬", text: "Har finest smil?"),
        Card(title: "Hvem i rommet", emoji: "🥺", text: "Er mest desperat?"),
        Card(title: "Hvem i rommet", emoji: "🍻", text: "Er den største fylliken?"),
        Card(title: "Hvem i rommet", emoji: "🍑", text: "Har finest rumpe?"),
        Card(title: "Hvem i rommet", emoji: "🌮", text: "Ligner mest på en taco? (taco er jo det beste som finnes, man velger jo ingrediensene selv)"),
        Card(title: "Hvem i rommet", emoji: "💌", text: "Drar på flest Tinderdates?"),
        Card(title: "Hvem i rommet", emoji: "🥴", text: "Er fullest?"),
        Card(title: "Hvem i rommet", emoji: "🌎", text: "Har hatt seg med flest nasjonaliteter?"),
        Card(title: "Hvem i rommet", emoji: "🍝", text: "Spiser mest pasta?"),
        Card(title: "Hvem i rommet", emoji: "💏", text: "Får kjæreste i år?"),
        Card(title: "90 spørsmål", text:"🍻SKÅL🍻"),

        Card(title: "Hvem i rommet", emoji: "⏰", text: "Oftest forsinket?"),
        Card(title: "Hvem i rommet", emoji: "👋", text: "Spruter mest?"),
        Card(title: "Hvem i rommet", emoji: "🏝", text: "Ville vært med på en øde øy?"),
        Card(title: "Hvem i rommet", emoji: "🌷", text: "Lukter best?"),
        Card(title: "Hvem i rommet", emoji: "🎤", text: "Synger finest?"),
        Card(title: "Hvem i rommet", emoji: "👔", text: "Har best stil?"),
        Card(title: "Hvem i rommet", emoji: "👆", text: "Er festens høyeste?"),
        Card(title: "Hvem i rommet", emoji: "👩🏼‍🍳", text:"Er best på kjøkkenet?"),
        Card(title: "Hvem i rommet", emoji: "🍷", text: "Blir mest drita i kveld?"),
        Card(title: "Hvem i rommet", emoji: "🎯", text: "Har vært festens midtpunkt?"),
        Card(title: "100 spørsmål",  text:"🍻SKÅL🍻"),
    ]
}
